# Working Papers

[Efficiency and Equity Effects of Electricity Metering: Evidence from Colombia](/files/electricity-metering.pdf)<br>

[Electricity Pricing for the Energy Transition](/files/electricity-pricing-energy-transition.pdf)<br>
(with [Frank Wolak](https://web.stanford.edu/group/fwolak/cgi-bin/))

[Reliability Options in Renewables-Dominated Electricity Markets](/files/capacity-payment-mechanism.pdf)<br>
(with [Frank Wolak](https://web.stanford.edu/group/fwolak/cgi-bin/))

[Why Are Connection Charges So High? An Analysis of the Electricity Sector in Sub-Saharan Africa](/files/why-are-connection-charges-so-high.pdf)<br>
(with [Moussa Blimpo](https://sites.google.com/site/mpblimpo/welcome-cv) and [Jevgenijs Steinbuks](http://www.steinbuks.info))


# Published Papers

[Competitive Effects of Entry in Gasoline Markets](/files/competitive-effects-entry-gasoline.pdf)<br>
(with [Lucas Davis](https://faculty.haas.berkeley.edu/ldavis/) and [Enrique Seira](http://enriqueseira.weebly.com))<br>
Accepted at *Journal of Industrial Economics*.<br>
2nd place in the *Premio Citibanamex de Economía*. [EI Blog Post](https://energyathaas.wordpress.com/2023/12/11/does-station-competition-drive-gas-prices/)

[Fueling Alternatives: Gas Station Choice and the Implications for Electric Charging](/files/fueling-alternatives.pdf)<br>
(with [Jackson Dorsey](https://www.jacksonfdorsey.com) and [Ashley Langer](https://www.ashleylanger.com))<br>
*American Economic Journal: Economic Policy*, Vol. 17, No. 1, February 2025.<br>
[Journal Website](https://www.aeaweb.org/articles?id=10.1257/pol.20220130) | [Online Appendix](/files/fueling-alternatives-appendix.pdf) | [NBER Digest](https://www.nber.org/digest/202206/design-trade-offs-electric-vehicle-charging-networks)

[Residential Electricity Consumption and Adaptation to Climate Change by Colombian Households](/files/electricity-consumption-and-adaptation.pdf)<br>
*Economics of Disasters and Climate Change*, Vol. 7, July 2023, 253–279.<br>
[Journal Website](https://doi.org/10.1007/s41885-023-00131-3) | [IDB Working Paper](https://www.econstor.eu/handle/10419/289924)

[Retail Pricing in Colombia to Support the Efficient Deployment of Distributed Generation and Electric Stoves](/files/retail-pricing-in-colombia.pdf)<br>
(with [Frank Wolak](https://web.stanford.edu/group/fwolak/cgi-bin/))<br>
*Journal of Environmental Economics and Management*, Vol. 110, October 2021, 102541.<br>
[Journal Website](https://doi.org/10.1016/j.jeem.2021.102541) | [IDB Working Paper](https://www.econstor.eu/handle/10419/234652)

[Self-regulation vs state regulation: Evidence from cinema age restrictions](/files/self-regulation-versus-state-regulation.pdf)<br>
(with [Ryan Lampe](https://www.ryanlampe.com))<br>
*International Journal of Industrial Organization*, Vol. 75, March 2021, 102708.<br>
[Journal Website](https://doi.org/10.1016/j.ijindorg.2021.102708)

[An Economic Perspective on Mexico's Nascent Deregulation of Retail Petroleum Markets](/files/mexico-deregulation-petroleum.pdf)<br>
(with [Lucas Davis](https://faculty.haas.berkeley.edu/ldavis/) and [Enrique Seira](http://enriqueseira.weebly.com))<br>
*Economics of Energy & Environmental Policy*, Vol. 8, No. 2, September 2019, 181-200.<br>
[Journal Website](https://doi.org/10.5547/2160-5890.8.2.ldav) | [EI Blog Post](https://energyathaas.wordpress.com/2016/07/11/move-over-pemex/)

[Infrastructure Quality and the Subsidy Trap](/files/infrastructure-quality-and-subsidy-trap.pdf)<br>
*American Economic Review*, Vol. 105, No. 1, January 2015, 35-66.<br>
[Journal Website](https://doi.org/10.1257/aer.20110572)

[Testing the convergence hypothesis: a new approach](/files/testing-the-convergence-hypothesis.pdf)<br>
(with [Erkin Bairam](https://www.researchgate.net/scientific-contributions/Erkin-I-Bairam-2033580085))<br>
*Economics Letters*, Vol. 64, 1999, 351-355.<br>
[Journal Website](https://doi.org/10.1016/S0165-1765(99)00099-3)


# Other Publications

[Diagnosing the Causes of the Recent El Niño Event and Recommendations for Reform](/files/diagnosing-el-nino.pdf)<br>
(with [Frank Wolak](https://web.stanford.edu/group/fwolak/cgi-bin/)).

[Book review: 'The Economics of Electricity Markets: Theory and Policy'](/files/book-review-electricity-markets.pdf)<br>
*Journal of Economic Literature*, Vol. 52, No. 2, 554--5.

[How Do Firms Exercise Unilateral Market Power? Evidence from a Bid-Based Wholesale 
Electricity Market](/files/how-do-firms-exercise-market-power.pdf)<br>
(with [Frank Wolak](https://web.stanford.edu/group/fwolak/cgi-bin/))<br>
In *Manufacturing Markets: Legal, Political and Economic Dynamics*, Eric Brousseau and Jean-Michel Glachant (eds), Cambridge University Press, 2014.

[Merger Analysis in Restructured Electricity Supply Industries: The Proposed PSEG and 
Exelon Merger (2006)](/files/merger-analysis-in-restructured-electricity.pdf)<br>
(with [Frank Wolak](https://web.stanford.edu/group/fwolak/cgi-bin/))<br>
In *The Antitrust Revolution: Economics, Competition and Policy*, John E. Kwoka and Lawrence J. White (eds), Oxford University Press, 2009.


# Older Working Papers

[Crude Oil Price Differentials and Pipeline Infrastructure](/files/oil-price-differentials-pipeline.pdf)<br>
[NBER Working Paper](https://www.nber.org/papers/w24170).

[Market Power in a Hydro-Dominated Wholesale Electricity Market](/files/market-power-hydro-dominated.pdf)<br>
(with [Frank Wolak](https://web.stanford.edu/group/fwolak/cgi-bin/)).

[Price Perceptions and Electricity Demand with Nonlinear Prices](/files/price-perceptions.pdf)<br>
(with [Robyn Meeks](http://www.robynmeeks.com)).

[Reliability, Appliance Choice, and Electricity Demand](/files/reliability-appliance-choice.pdf)<br>

[Step on It: A New Approach to Improving Vehicle Fuel Economy](/files/step-on-it-fuel-economy.pdf)<br>
(with [Ashley Langer](https://www.ashleylanger.com)).

[Vertical Integration and Price Differentials in the U.S. Crude Oil Market](/files/vertical-integration-price-differentials.pdf)<br>
*Public Utility Research Center Prize for the Best Paper in Regulatory Economics*


# Work in Progress

Avoiding tax on cars and its enviromental implications in Mexico<br>
(with [Pedro Liedo](https://are.ucdavis.edu/people/grad-students/phd/pedro-liedo-orozco/))

Financing the energy transition: Evidence from natural gas adoption

Market power in cost-based wholesale electricity markets: Evidence from Mexico

