I will be on sabbatical from ITAM in the 2025-26 academic year.

# Industrial Organization (Spring 2025)

This course will study how firms compete with each other in imperfectly competitive markets. We will start with a brief review of the basic concepts from consumer and producer theory. The remainder of the course will focus on firms' price and non-price strategies in the case of oligopoly. Examples of the topics covered include price discrimination, collusion, horizontal mergers, predatory pricing, vertical restraints, product differentiation, research and development, and network effects.

By the end of this course, you should be able to do the following:

1. understand the standard economic models for the analysis of imperfectly competitive markets;

2. apply these models to explain the real-world behavior of firms in the Mexican economy and elsewhere; and

3. find relevant questions and data for writing an undergraduate thesis or *tesina* in the field of industrial organization.

The required textbook for the course is Luís Cabral, [Introduction to Industrial Organization](https://mitpress.mit.edu/9780262035941/introduction-to-industrial-organization/), Second Edition.

[Syllabus](/files/2025-S1-io-syllabus.pdf)


# Advanced Microeconometrics (Spring 2025)

This course will study the applications of econometrics to the analysis of cross-sectional and panel datasets. First, we will review the Ordinary Least Squares ("OLS") model and discuss the issues that come up in practical applications of OLS. Second, we will study three types of econometric model that are frequently used in empirical work: the instrumental variables model, limited dependent variable models, and panel data models. Third, we will analyze the causal inference framework and review so-called "quasi-experimental" methods such as differences-in-differences and regression discontinuity. Finally, we will compare structural estimation models to the causal inference framework, using the differentiated product demand model as an example.

By the end of this course, you should be able to do the following:

1. understand and apply the econometric methods that will be most useful for writing an undergraduate or graduate thesis in economics;

2. critically read and understand the econometric methods used in recent papers in applied microeconomics fields; and

3. write programs in Python for simulation and data analysis.

[Syllabus](/files/2025-S1-metrics-syllabus.pdf)
