[CV](/files/mcrae-cv.pdf)

### Academic positions

- **ITAM**, Assistant Professor, Centro de Investigación Económica and Department of Economics, 2016-present.
	
- **University of Michigan**, Assistant Professor, Department of Economics, 2010-2016.

- **Stanford University**, Visiting Scholar, Program on Energy and Sustainable Development, Spring 2014.

- **University of California, Berkeley**, Visiting Scholar, Energy Institute at Haas, Fall 2013.


### Education

- **Stanford University**, Stanford, CA
  - Ph.D., Economics, 2010
  - M.A., Economics, 2010

- **University of Auckland**, Auckland, New Zealand
  - B.Sc.(Hons.), Mathematics, 1999

- **University of Otago**, Dunedin, New Zealand
  - B.Com.(Hons.), Economics, 1998


### Fellowships, grants, and sponsored projects

- Weiser Center for Emerging Democracies Faculty Grant, 2015

- University of Michigan Office of Research award, 2015

- MITRE Faculty Research Grant, 2013, 2015

- Rackham Spring/Summer Research Award, 2011

- Stanford Institute for Economic Policy Research Kapnick Fellowship, 2009-10

- Martin Lee Johnson Stanford Graduate Fellowship, 2003-08


### Awards and prizes

- Citibanamex Economics Prize (2nd place), 2022.

- Public Utility Research Center Prize for the Best Paper in Regulatory Economics at the 13th Annual International Industrial Organization Conference, 2015.

- Stanford Institute for Economic Policy Research, Claire and Ralph Landau Student Working Paper Prize, 2010.

- University of Auckland Dean of Science Prize, 1998.

- University of Auckland Collins Prize in Mathematics, 1998.

- University of Otago John Waddell Hayward Award in Commerce, 1996.


### Other employment

- Credit Suisse First Boston, Auckland, New Zealand
  - Investment Banking Analyst, 1999-2001
  - Investment Banking Associate, 2002


